In [24]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 파일 경로
file_path = "C:/iris.csv"

# 데이터 로드
df = pd.read_csv(file_path)

# 데이터 확인
print(df.head())
print(df.columns)

# 🔹 데이터 전처리
X = df.iloc[:, :-1]  # 마지막 열(Name)을 제외한 feature 선택
y = df.iloc[:, -1]   # 마지막 열(Name)을 target으로 설정

# 클래스(Label) 문자열을 숫자로 변환
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # Iris-setosa → 0, Iris-versicolor → 1, Iris-virginica → 2

# 🔹 훈련/테스트 데이터 분할 (80% 훈련, 20% 테스트)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 🔹 모델 학습 및 평가
models = {
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "SVM": SVC(),
    "Logistic Regression": LogisticRegression(max_iter=200)
}

for name, model in models.items():
    model.fit(X_train, y_train)  # 모델 학습
    y_pred = model.predict(X_test)  # 예측
    acc = accuracy_score(y_test, y_pred)  # 정확도 계산

    print(f"\n{name} Accuracy: {acc:.4f}")
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    print("Classification Report:")
    print(classification_report(y_test, y_pred))

    # 🔹 실제 값 vs 예측 값 비교 (5개 샘플 출력)
    print("🔍 실제값 (y_test) vs 예측값 (y_pred) (5개 샘플)")
    print(f"y_test: {y_test[:5].tolist()}")
    print(f"y_pred: {y_pred[:5].tolist()}")
    print("-" * 50)


   SepalLength  SepalWidth  PetalLength  PetalWidth         Name
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa
Index(['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'Name'], dtype='object')

Decision Tree Accuracy: 1.0000
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

🔍 실제값 (y_test) vs 예측값 (y_pred